//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelConcertos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente: BaseNotifyPropertyChanged, ICloneable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.OS = new HashSet<OS>();
        }
        private int _Id_Cliente;
        public int Id_Cliente
        {
            get { return _Id_Cliente; }
            set { SetField(ref _Id_Cliente, value); }
        }

        private string _Nome;
        public string Nome
        {
            get { return _Nome; }
            set { SetField(ref _Nome, value); }
        }

        private string _Sobrenome;
        public string Sobrenome
        {
            get { return _Sobrenome; }
            set { SetField(ref _Sobrenome, value); }
        }

        private string _Email;
        public string Email
        {
            get { return _Email; }
            set { SetField(ref _Email, value); }
        }

        private string _Cpf;
        public string Cpf
        {
            get { return _Cpf; }
            set { SetField(ref _Cpf, value); }
        }

        private string _Telefone;
        public string Telefone
        {
            get { return _Telefone; }
            set { SetField(ref _Telefone, value); }
        }

        private string _Endereco;
        public string Endereco
        {
            get { return _Endereco; }
            set { SetField(ref _Endereco, value); }
        }




        /*public int Id_Cliente { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string Email { get; set; }
        public string Cpf { get; set; }
        public string Telefone { get; set; }
        public string Endereco { get; set; }*/

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OS> OS { get; set; }

        public object Clone()
        {
            return this.MemberwiseClone();

        }
    }

    public abstract class BaseNotifyPropertyChanged : System.ComponentModel.INotifyPropertyChanged
    {
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void SetField<T>(ref T field, T value, [System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            if (!EqualityComparer<T>.Default.Equals(field, value))
            {
                field = value;
                RaisePropertyChanged(propertyName);
            }
        }
        protected void RaisePropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
