//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelConcertosEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OS : BaseNotifyPropertyChanged, ICloneable
    {


        private int _Id_OS;
        public int Id_OS
        {
            get { return _Id_OS; }
            set { SetField(ref _Id_OS, value); }
        }

        private string _Descricao;
        public string Descricao
        {
            get { return _Descricao; }
            set { SetField(ref _Descricao, value); }
        }

        private decimal _Valor;
        public decimal Valor
        {
            get { return _Valor; }
            set { SetField(ref _Valor, value); }
        }
        [Required]
        private DateTime? _Data_Entrada;
        public DateTime? Data_Entrada
        {
            get { return _Data_Entrada; }
            set { SetField(ref _Data_Entrada, value); }
        }
        [Required]
        private DateTime? _Data_Saida;
        public DateTime? Data_Saida
        {
            get { return _Data_Saida; }
            set { SetField(ref _Data_Saida, value); }
        }

        private string _Status;
        public string Status
        {
            get { return _Status; }
            set { SetField(ref _Status, value); }
        }

        private string _Situacao;
        public string Situacao
        {
            get { return _Situacao; }
            set { SetField(ref _Situacao, value); }
        }
        [Required]
        private int _ClienteId_Cliente;
        public int ClienteId_Cliente
        {
            get { return _ClienteId_Cliente; }
            set { SetField(ref _ClienteId_Cliente, value); }
        }
        [Required]
        private int _PranchaId_Prancha;
        public int PranchaId_Prancha
        {
            get { return _PranchaId_Prancha; }
            set { SetField(ref _PranchaId_Prancha, value); }
        }

      public virtual Cliente Cliente { get; set; }
      public virtual Prancha Prancha { get; set; }

        public object Clone()
        {
            return this.MemberwiseClone();
        }

    }
}
