//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelConcertos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OS
    {
        public int Id_OS { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime Data_Entrada { get; set; }
        public System.DateTime Data_Saida { get; set; }
        public string Status { get; set; }
        public string Situacao { get; set; }
        public int ClienteId_Cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Prancha Prancha { get; set; }
    }
}
