//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelConcertos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prancha
    {
        public int Id_Prancha { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Medida { get; set; }
        public string Cor { get; set; }
        public int QtdQuilhas { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual OS OS { get; set; }
    }
}
