//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelConcertosEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prancha: BaseNotifyPropertyChanged, ICloneable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prancha()
        {
            this.OS = new HashSet<OS>();
        }

        private int _Id_Prancha;
        public int Id_Prancha
        {
            get { return _Id_Prancha; }
            set { SetField(ref _Id_Prancha, value); }
        }

        private string _Marca;
        public string Marca
        {
            get { return _Marca; }
            set { SetField(ref _Marca, value); }
        }

        private string _Modelo;
        public string Modelo
        {
            get { return _Modelo; }
            set { SetField(ref _Modelo, value); }
        }

        private string _Cor;
        public string Cor
        {
            get { return _Cor; }
            set { SetField(ref _Cor, value); }
        }

        private int _QtdQuilhas;
        public int QtdQuilhas
        {
            get { return _QtdQuilhas; }
            set { SetField(ref _QtdQuilhas, value); }
        }

        private string _Medida;
        public string Medida
        {
            get { return _Medida; }
            set { SetField(ref _Medida, value); }
        }

        /* public int Id_Prancha { get; set; }
         public string Marca { get; set; }
         public string Modelo { get; set; }
         public string Cor { get; set; }
         public int QtdQuilhas { get; set; }
         public string Medida { get; set; }*/

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OS> OS { get; set; }

        public object Clone()
        {
            return this.MemberwiseClone();
        }
    }
}
